### ISSUE TITLE
discussion: pluraliser le nom du module

### ISSUE THREAD

**Issue by adipasquale** [betagouv/dsfr-view-components#10]
`DsfrComponents` au lieu de `DsfrComponent` ?

- [ ] voir d'autres gems de librairie de composants pour se faire une idee

**Comment by freesteph** [comment]
Sur ce point je préfère rester sur le fork (qui au passage est écrite par un excellent rubyiste – le code est très rubidiomatique). Les classes finales sont consistantes dans le nom de l'héritage (`DsfrComponent::AlertComponent`). Si tu trouves un bon exemple je veux bien réétudier la question.

**Comment by adipasquale** [comment]
c'est vrai que viewcomponent lui meme est au singulier

**Comment by adipasquale** [comment]
discuté, on reste tel quel
