### ISSUE TITLE
déployer la documentation

### ISSUE THREAD

**Issue by adipasquale** [betagouv/dsfr-view-components#7]
demander un sous-domaine incubateur.net ? ou alors juste sur github.io

**Comment by adipasquale** [comment]
il semble que pour l'instant le guide de govuk soit déployé sur netlify mais on veut peut etre le faire sur github pour eviter d'avoir un outil en plus ?

**Comment by freesteph** [comment]
ouais sur GitHub c'est très bien pour le moment
