### ISSUE TITLE
discussion: renommer le repo et la gem

### ISSUE THREAD

**Issue by adipasquale** [betagouv/dsfr-view-components#9]
à l'échelle de beta gouv ce n'est peut-être pas très fair de "squatter" le nom dsfr-components qui sera probablement ambigu avec d'autres frameworks de components dans d'autres langages il me semble non ?

et même à l'échelle de ruby il y aura peut-être une version alternative avec un autre framework comme phlex ? (je rêve un peu)

je propose `dsfr-view-components` pour le nom de repo et de gem

**Comment by adipasquale** [comment]
ping @freesteph qu'en penses-tu?

**Comment by freesteph** [comment]
Agreed 👍

**Comment by adipasquale** [comment]
done !
