### ISSUE TITLE
unfork de govuk

### ISSUE THREAD

**Issue by adipasquale** [betagouv/dsfr-view-components#99]
https://ralphjsmit.com/unfork-github-repo

pour eviter les erreurs de prs et ne plus avoir le message de divergence des commits

**Comment by adipasquale** [comment]
est-ce que ca te va si je fais lq demande d'unfork @freesteph ? j'ai encore refait une PR vers govuk ce matin 🤦

**Comment by freesteph** [comment]
Done !
